[buildPlans.kashevsky-hyperfocus]
family = "Kashevsky Hyperfocus"
spacing = "quasi-proportional-extension-only"
serifs = "sans"
no-cv-ss = true
no-ligation = true

  [buildPlans.iosevka-hyperlegible.variants]
  inherits = "ss15"

    [buildPlans.iosevka-hyperlegible.variants.design]
    capital-b = "standard-serifless"
    capital-d = "standard-serifless"
    capital-g = "toothless-corner-serifless-hooked"
    capital-h = "serifless"
    capital-i = "short-serifed"
    capital-j = "serifless"
    capital-k = "straight-serifless"
    capital-m = "hanging"
    capital-q = "crossing"
    capital-r = "standing"
    capital-w = "straight-flat-top"
    capital-z = "straight-serifless"
    a = "double-storey-tailed"
    b = "toothed"
    d = "toothed-serifless"
    f = "flat-hook-serifed"
    g = "single-storey-serifless"
    i = "serifed"
    j = "serifless"
    k = "straight-serifless"
    m = "top-left-serifed"
    n = "straight"
    q = "straight"
    r = "serifless"
    t = "flat-hook"
    y = "straight-turn"
    zero = "unslashed"
    one = "no-base"
    two = "straight-neck"
    three = "flat-top"
    four = "closed"
    five = "vertical-upper-left-bar"
    six = "straight-bar"
    seven = "straight-serifless"
    eight = "two-circles"
    nine = "straight-bar"
    asterisk = "turn-hex-high"
    pilcrow = "low"
    paren = "large-contour"
    brace = "straight"
    number-sign = "upright"
    ampersand = "upper-open"
    at = "fourfold"
    dollar = "open"
    percent = "rings-continuous-slash"
    bar = "natural-slope"
    ascii-single-quote = "raised-comma"
    ascii-grave = "raised-inverse-comma"
    question = "smooth"

    [buildPlans.kashevsky-hyperfocus.variants.italic]
    l = "serifed"
    v = "straight-motion-serifed"
    x = "curly-serifless"
    z = "straight-serifless"

[buildPlans.kashevsky-hyperfocus.widths.normal]
shape = 600
menu = 5
css = "normal"
